import Navbar from './Components/Navbar/Navbar'
import './globals.css'
import { Inter,Cairo as CairoFont} from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const Cairo = CairoFont({ 
    subsets: ['arabic'],

})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Cairo.className}>
          <Navbar/>
          {children}
        </body>
    </html>
  )
}
